### ISSUE TITLE
Data Dictionary (Phase 5)

### ISSUE THREAD

**Issue by bubbathan** [bubbathan/cs5800_final_project#7]
In this phase, your task is to create a data dictionary. A data dictionary defines the basic organization of the tables which are to be stored in the database. In a proper data dictionary, the tables, the attributes (or columns) of the tables are demonstrated. The relationship between attributes are also shown (foreign key relationships). Different from the relational model, in a data dictionary, you specify the domain of each attribute, as well as other constraints that might be important during the implementation phase. Note that domain of an attribute includes syntactic and semantic interpretations of an attribute. For example, the domain for birth date of an employee is a ‘time’ (or ‘date’, or datetime in some DBMSs). However, you will only store the day, month, and year values. Similarly, the year for a car can also be stored using ‘datetime’ type objects, but you only store the year. Example for other constraints on a birth date is that the time cannot be more than the current time instance.

**Comment by skal-chin** [comment]
I edited the dictionary a little bit to more reflect the tables and their structure. I added Staff, Doctor, and Procedure and add a 'References' constraint to their subclasses. I am going to close this issue.
